<!DOCTYPE html>
<html lang="ko">
<title>23강 Error 다루기</title>

<body>
  <script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>

  <div id="root"></div>

  <script type="text/babel">
    const rootElement = document.getElementById('root')

    // ErrorBoundary: 에러바운더리로 감싸진 자식에서 에러가 나면 특정한 화면을 보여준다. 이거는 class 컴포넌트로 만들어야함
    // 아래 코드는 화면에 App, There is some error...가 그려졌을것이다.
    // App은 그려지고 에러가 있는 Child 컴포넌트는 못그렸지만 에러가 났을 때 보여주고싶은 UI는 보여주었다.
    class ErrorBoundary extends React.Component {
      state = { error: null }
      static getDerivedStateFromError(error) {
        return { error }
      }

      render() {
        const { error } = this.state
        if (error) {
          // return (<p>There is some error...</p>) // fallback 사용하지 않고 바로 그려버리기
          return this.props.fallback  // fallback 사용
        }

        return this.props.children
      }
    }

    const Child = () => {
      throw new Error('Something wrong...')
      return (
        <p>Child...</p>
      )
    }

    const Fallback = (error) => {
      return <p>THERE IS SOME ERROR...</p>
    }

    // ErrorBoundary 컴포넌트가 에러가 났을 때 어떤 컴포넌트를 그릴지를 스스로 판단하는 것이 아니라 내가 직접 넣어주려면 fallback을 사용한다.
    const App = () => {
      return (
        <>
          <p>App</p>
          {/* <Child /> ErrorBoundary 사용하지 않았을 때는 에러로 인해 전체 화면이 그려지지 않음 */}

          {/* <ErrorBoundary fallback={<p>There is some error...!!</p>}> */}
          <ErrorBoundary fallback={<Fallback />}>
            <Child />
          </ErrorBoundary>
        </>
      )
    }

    // Child의 error message를 alert하려면
    /*
    class ErrorBoundary extends React.Component {
      state = { error: null }
      static getDerivedStateFromError(error) {
        return { error }
      }

      render() {
        const { error } = this.state
        if (error) {
          return <this.props.fallback error={error} />
        }

        return this.props.children
      }
    }

    const Child = () => {
      throw new Error('Something wrong...')
      return (
        <p>Child...</p>
      )
    }

    const Fallback = ({ error }) => {
      alert(error.message)
      return <p>THERE IS SOME ERROR...</p>
    }

    const App = () => {
      return (
        <>
          <p>App</p>
          <ErrorBoundary fallback={Fallback}>
            <Child />
          </ErrorBoundary>
        </>
      )
    }
    */

    ReactDOM.render(<App />, rootElement)

    // try catch문 처럼 어떻게 에러를 핸들링 할 수 있을까? => Error boundary
    // ErrorBoundary는 왜 함수형 컴포넌트가 아닌 클래스형 컴포넌트로 만들어야만 하는가? => getDerivedStateFromError 에러가 났을 때 상태값을 처리하는 함수 자체를 클래스 컴포넌트에서만 제공하기 때문
    // ErrorBoundary의 역할 => 에러가 났을 때 상위 요소까지 전파하여 렌더링 되지 않는(화면이 그려지지 않는) 이슈가 발생하는데 에러바운더리 컴포넌트를 정의함으로써 에러가 났을 때 그 값을 받아서 화면을 못그리게 하는 것이 아니라 fallback이나 다른 값을 그려줄 수 있다.
  </script>
</body>

</html>